heat_template_version: newton

description: >
  Gluon service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MonitoringSubscriptionGluon:
    default: 'overcloud-gluon'
    type: string
outputs:
  role_data:
    description: Role data for the Gluon role.
    value:
      service_name: gluon
      monitoring_subscription: {get_param: MonitoringSubscriptionGluon}
      config_settings:
        tripleo.gluon.firewall_rules:
          '142 gluon':
            dport:
              - 2705
      step_config: |
        include tripleo::profile::base::gluon
